// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Spookify
{
	public partial class ConfigViewController : UIViewController
	{
		public ConfigViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			var appVersionString = NSBundle.MainBundle.ObjectForInfoDictionary("CFBundleShortVersionString");
			var appBuildString = NSBundle.MainBundle.ObjectForInfoDictionary("CFBundleVersion");

			this.VersionLabel.Text = string.Format("© 2016 Markus Fischer, Version {0} ({1})",appVersionString,appBuildString);
			UpdateStatus ();
		}

		void UpdateStatus()
		{
			if (CurrentPlayer.Current.AuthPlayer != null &&
			    CurrentPlayer.Current.AuthPlayer.Session != null) {
				this._StatusRefreshLabel.Text = string.Format ("Session: {0}  Expiration: {1}",
					CurrentPlayer.Current.AuthPlayer.Session.IsValid ? "valid" : (CurrentPlayer.Current.TriggerWaitingForSessionRenew ? "renew pending" : "invalid"),
					CurrentPlayer.Current.AuthPlayer.Session.ExpirationDate.NSDateToDateTime ().ToString ("G")
				);
			} else
				this._StatusRefreshLabel.Text = "no Session";
			
			var player = CurrentPlayer.Current.RawPlayer;
			if (player == null)
				this._StatusSwapLabel.Text = "no player";
			else {
				this._StatusSwapLabel.Text = string.Format ("Player created, {0}, {1}",
					player.LoggedIn ? "logged in" : (CurrentPlayer.Current.TriggerWaitingForLogin ? "login pending" : "not logged in"),
					player.IsPlaying ? "playing" : "not playing");
			}
		}

		public string Info = @"Hörbücher bei Spotify finden und anhören.   Die Idee zu dieser App kam mir, als ich versuchte ein Hörbuch bei Spotify bei einer Schitour anzuhören - die Spotify iOS App hat die Kapitel geshuffelt und ich war oben völlig verwirrt. So konnte es nicht weiter gehen, eine Lösung musste her...hier ist sie...leider ohne offline Funktionaltität, denn dies bietet die API von Spotify nicht an.  Impressum: Fischer & Schaefers GbR
Stollbergstrasse 6
80539 München
E-Mail: gbr @ consultdot.net 

Geschäftsführende Gesellschafter:
Bernhard Schaefers, Markus Fischer

Fischer & Schaefers GbR ist eine Gesellschaft bürgerlichen Rechts mit Sitz in München

Umsatzsteuer-ID-Nr.: DE243564719  Haftungsbeschränkung: 
Die Inhalte der App wurden mit größtmöglicher Sorgfalt und nach bestem Gewissen erstellt. Dennoch übernimmt der Anbieter der App keine Gewähr für die Aktualität, Vollständigkeit und Richtigkeit der bereitgestellten Inhalte.

Die meisten Inhalte dieser App, insbesondere Texte, Bilder und Audioinhalte, stammen von Spotify, Inhaltsangaben der Bücher stammen von google.  Für die Inhalte und Richtigkeit der bereitgestellten Informationen ist der jeweilige Anbieter der Daten verantwortlich.  Externe Links: 
Die App enthält sog. „externe Links“ (Verlinkungen) zu anderen Webseiten, auf deren Inhalt der Anbieter der Webseite keinen Einfluss hat. Aus diesem Grund kann der Anbieter für diese Inhalte auch keine Gewähr übernehmen.
Für die Inhalte und Richtigkeit der bereitgestellten Informationen ist der jeweilige Anbieter der verlinkten Webseite verantwortlich. Zum Zeitpunkt der Verlinkung waren keine Rechtsverstöße erkennbar. Bei Bekanntwerden einer solchen Rechtsverletzung wird der Link umgehend entfernen.  Urheberrecht/Leistungsschutzrecht: 
Die auf dieser Webseite veröffentlichten Inhalte, Werke und bereitgestellten Informationen unterliegen dem deutschen Urheberrecht und Leistungsschutzrecht. Jede Art der Vervielfältigung, Bearbeitung, Verbreitung, Einspeicherung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedarf der vorherigen schriftlichen Zustimmung des jeweiligen Rechteinhabers. ";
	}
}
