// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Spookify
{
	public partial class GenreTableViewCell : UITableViewCell
	{
		public GenreTableViewCell (IntPtr handle) : base (handle)
		{
		}
		public override UIEdgeInsets LayoutMargins {
			get {
				return UIEdgeInsets.Zero;
			}
			set {
				base.LayoutMargins = value;
			}
		}		
	}
}

