// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Spookify
{
	public partial class HoerbuchTableViewCell : UITableViewCell
	{
		public PlaylistBook CurrentPlaylistBook { get; set; }
		public AudioBook CurrentAudioBook { get; set; }

		public HoerbuchTableViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
